import PDFDocument from 'pdfkit';

/**
 * Generates a clean PDF document buffer from Markdown/Plaintext content.
 */
export const generatePdfBuffer = async (content, title = 'Cortex AI Document') => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header Banner
      doc.fillColor('#0F172A').rect(0, 0, 595.28, 80).fill();
      doc.fillColor('#38BDF8').fontSize(22).font('Helvetica-Bold').text(title, 50, 25);
      doc.fillColor('#94A3B8').fontSize(10).font('Helvetica').text('Generated by Cortex Multi-Agent AI Platform', 50, 52);

      doc.moveDown(4);
      doc.fillColor('#1E293B').font('Helvetica');

      // Simple Markdown line parser
      const lines = content.split('\n');
      for (const line of lines) {
        if (line.startsWith('# ')) {
          doc.moveDown(1);
          doc.fillColor('#0F172A').fontSize(18).font('Helvetica-Bold').text(line.replace('# ', ''));
          doc.fillColor('#1E293B').font('Helvetica').fontSize(11);
        } else if (line.startsWith('## ')) {
          doc.moveDown(0.8);
          doc.fillColor('#0369A1').fontSize(14).font('Helvetica-Bold').text(line.replace('## ', ''));
          doc.fillColor('#1E293B').font('Helvetica').fontSize(11);
        } else if (line.startsWith('### ')) {
          doc.moveDown(0.5);
          doc.fillColor('#334155').fontSize(12).font('Helvetica-Bold').text(line.replace('### ', ''));
          doc.fillColor('#1E293B').font('Helvetica').fontSize(11);
        } else if (line.startsWith('- ') || line.startsWith('* ')) {
          doc.fontSize(11).font('Helvetica').text(`  •  ${line.substring(2)}`);
        } else if (line.trim().length === 0) {
          doc.moveDown(0.4);
        } else {
          doc.fontSize(11).font('Helvetica').text(line);
        }
      }

      // Footer
      doc.fontSize(9).fillColor('#94A3B8').text(
        `Generated on ${new Date().toLocaleDateString()} | Cortex Multi-Agent Platform`,
        50,
        780,
        { align: 'center', width: 495.28 }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
